name       : perl-sub-info
version    : 0.002
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Sub-Info-0.002.tar.gz : ea3056d696bdeff21a99d340d5570887d39a8cc47bff23adfc82df6758cdd0ea
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Sub::Info - Tool for inspecting subroutines.
description: |
    Tool to inspect subroutines.
builddeps  :
    - perl-importer
    - perl-test-simple
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
